version: 2
updates:
  - package-ecosystem: docker
    directory: /
    target-branch: Preview
    schedule:
      interval: daily
    commit-message:
      prefix: "build(deps)"
  - package-ecosystem: npm
    directory: /
    target-branch: Preview
    schedule:
      interval: daily
      time: "06:00"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      runtime-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "chore(deps)"
      include: scope

  - package-ecosystem: github-actions
    directory: /
    target-branch: Preview
    schedule:
      interval: daily
      time: "06:15"
      timezone: Europe/Lisbon
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: "ci(deps)"
