-- External, read-only API credentials for stable integrations.
-- Keys are generated by the Vercel API, returned once, and stored only as SHA-256 hashes.

create table if not exists public.external_api_clients (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 120),
  description text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  revoked_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.external_api_keys (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.external_api_clients(id) on delete cascade,
  key_prefix text not null,
  key_hash char(64) not null unique,
  scopes text[] not null default array['summaries:read']::text[],
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  last_used_at timestamptz,
  request_count bigint not null default 0 check (request_count >= 0),
  rate_window_start timestamptz,
  rate_window_count integer not null default 0 check (rate_window_count >= 0),
  metadata jsonb not null default '{}'::jsonb,
  check (cardinality(scopes) > 0)
);

create index if not exists external_api_clients_campaign_idx
  on public.external_api_clients(campaign_id, created_at desc);

create index if not exists external_api_keys_client_idx
  on public.external_api_keys(client_id, created_at desc);

create index if not exists external_api_keys_active_idx
  on public.external_api_keys(client_id, expires_at)
  where revoked_at is null;

alter table public.external_api_clients enable row level security;
alter table public.external_api_keys enable row level security;

-- Browser clients never query these tables through PostgREST. Management and
-- API authentication are performed by the server-side Postgres connection.
revoke all privileges on public.external_api_clients from public, anon, authenticated;
revoke all privileges on public.external_api_keys from public, anon, authenticated;

notify pgrst, 'reload schema';
